esphome:
  name: air_sensor_v1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air Sensor V1 Fallback Hotspot"
    password: "qboO6ocOSf6x"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

uart:
  rx_pin: D2
  tx_pin: D1
  baud_rate: 9600

sensor:
  - platform: mhz19
    co2:
      name: "MH-Z19 CO2 Value"
    update_interval: 60s
    automatic_baseline_calibration: true